apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-bitflow
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-bitflow
subjects:
- kind: ServiceAccount
  name: prometheus-bitflow
  namespace: default
