apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-bitflow
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
