apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: bitfow
  name: prometheus-bitflow
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web
    nodePort: 30910
  selector:
    app: prometheus
    prometheus: bitflow
